### ISSUE TITLE
Error in /usr/lib64/codecs.py

### ISSUE THREAD

**Issue by BusinessKid** [StevenMaude/nitroradical#13]
I grabbed this and tried it with /usr/bin/python ==> python2. It failed on the "import dshelpers" line,  so I decided I was a twit. On python3, I get this:
--bash-5.1$ nitroradical.py films
INFO:root:Downloading page 1
INFO:sw.ds.helpers:Download http://www.bbc.co.uk/iplayer/categories/films/all?sort=atoz&page=1
Traceback (most recent call last):
  File "/usr/local/bin/nitroradical.py", line 165, in <module>
    main()
  File "/usr/local/bin/nitroradical.py", line 156, in main
    print(json.dumps(items, indent=4))
  File "/usr/lib64/python3.9/codecs.py", line 378, in write
    self.stream.write(data)
TypeError: write() argument must be str, not bytes
bash-5.1$ 
--
Now, you're importing codecs, so I presume it  works for you. Python3 is version 3.9.1. I'm a hardware head, never got too deep in programming. Any ideas?

**Comment by StevenMaude** [comment]
Thanks for trying this out! :wave:

This code was originally a proof-of-concept made long ago for [discussing](https://lists.infradead.org/pipermail/get_iplayer/2014-October/006303.html) an issue relating to [get_iplayer](https://github.com/get-iplayer/get_iplayer)

The failure here is a Python issue as this code was written with Python 2 in mind (as the `from __future__…` imports). I've fixed that in #14. Then I found that the code doesn't actually do anything useful any longer: the BBC have changed their site structure. 

So I've also done a quick fix for that in #14 which I'll merge shortly.

By the way, I don't really make much in the way of guarantees with this, because I've only spent another hour working on it. But it may be enough for you to use as a starting point for something else, should you wish.

**Comment by BusinessKid** [comment]
I'm grateful for the code, as someone who spent his career in hardware. The python2/python3 thing is a mess, but python2 is EOL  or imminently EOL. Many distros have /usr/bin/python pointing at /usr/bin/python3 anyhow. It's good for an hour's work! I hear javascript was originally written in a weekend.

**Comment by StevenMaude** [comment]
No problem!

> I hear javascript was originally written in a weekend.

I'm not that good of a developer! :wink:

**Comment by BusinessKid** [comment]
Neither was he!

 
 

Sent: Monday, June 21, 2021 at 6:22 PM

**Comment by BusinessKid** [comment]
Hey Steven,

 

I just trien your latest iteration of nitroradical.py, and even from (geo-ip blocked)ireland it appears to do the business!  I had to edit to ensure it called python3. ThenI get output such as:

 

--

 "title": "The People of Paradise \u2014 5. Canoes and Coconut Crabs",
        "synopsis": "David Attenborough retraces his search to find the rare Fijian double canoe. (1960)",
        "url": "https://www.bbc.co.uk/iplayer/episode/p00y20lw/the-people-of-paradise-5-canoes-and-coconut-crabs"
--

 

that isn't a url, presumably a directory where there's files. The best progress is probably made from there with with youtube-dl. How do those urls typically finish?

 
 

Sent: Monday, June 21, 2021 at 6:22 PM

**Comment by StevenMaude** [comment]
Sorry for the delay in replying; have been a little busy.

> that isn't a url, presumably a directory where there's files. The best progress is probably made from there with with youtube-dl. How do those urls typically finish?

With get_iplayer, that type of URL works for me. Not sure about youtube-dl.

There is a slight complication in that:

1. The current code only pulls the episodes as listed for a category.
2. The BBC site only shows the most recent episode in the listing for a category, even if more episodes are available; see #1. This could be fixed; you'd have to modify the code so that it:
    1. Keeps a list of the programme page URLs for a category.
    2. Visits each programme page URL.
    3. Processes the list of episodes from the embedded JSON in each of those programme pages.
    4. Takes details of every episode from every programme page to generate the full list.
